### ISSUE TITLE
Server side mod?

### ISSUE THREAD

**Issue by frVasili** [ugackMiner53/DiscordProximity#7]
Hello! I understand this mod was intended to be one without any server-side software, however I would like to be able to implement a mod like this without my players needing to install it. Also, all other server-side only mods I can find don't work with fabric. I completely understand if you're not looking into expanding to server-side mods though. Thank you!

**Comment by ugackMiner53** [comment]
Unfortunately, something like this just isn't possible with the way that mc works right now. In order to get access to things like the microphone, you need to have something client sided installed.

(and, for the record, it's probably a good thing that servers can't get access to your microphone without the user's permission)

If you do find another mod which can do this, please let me know!

**Comment by frVasili** [comment]
A mod I found which seems to be server-side is [Skoice](https://www.spigotmc.org/resources/skoice-proximity-voice-chat.82861/), which seems to rely on a Discord bot that connects to each players Minecraft account. I haven't tried this yet as my server is running off of Fabric, and this mod doesn't natively support Fabric. Also Carboard doesn't have a 1.19.3 version yet, so I couldn't use that either. Thank you for taking the time to reply!

**Comment by ugackMiner53** [comment]
I didn't think of Skoice! Using a Discord Bot in order to connect players to different voice channels depending on where they are is certainly a valid way to do proximity chat! Unfortunately, this mod is geared towards specifically running _without_ any server-sided code, and I feel that incorporating a version of Skoice into the mod would detract from its goal to be a proximity mod that can be used without a server.

I do wish you luck on your journey to get Skoice (or a similar alternative) working on your server!
